'use client';

import Link from 'next/link';
import { useLanguage } from '@/lib/i18n/LanguageContext';
import LanguageSelector from '@/components/LanguageSelector';

export default function LegalNoticePage() {
  const { t } = useLanguage();

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 flex flex-col justify-between">
      {/* Header */}
      <header className="bg-slate-900 text-white px-4 sm:px-6 py-4 flex items-center justify-between shadow-md">
        <div className="flex items-center space-x-3">
          <Link href="/login" className="flex items-center space-x-2.5 hover:opacity-90 transition-opacity">
            <img
              src="/icons/icon-192x192.png"
              alt="Trip Zoo"
              className="w-9 h-9 rounded-xl shadow-sm border border-slate-700 object-cover shrink-0"
            />
            <span className="font-black text-lg tracking-tight text-blue-400">{t('common.appName')}</span>
          </Link>
        </div>
        <div className="flex items-center space-x-2">
          <LanguageSelector variant="header" />
          <Link
            href="/login"
            className="text-xs bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white px-3 py-1.5 rounded-xl border border-slate-700 font-bold transition-all"
          >
            ← {t('common.back')}
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-3xl w-full mx-auto px-4 py-8 sm:py-12 space-y-6 flex-1">
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 sm:p-8 space-y-6">
          <div className="border-b border-slate-100 pb-4">
            <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">
              {t('common.legalNotice')}
            </h1>
            <p className="text-xs text-slate-400 mt-1 font-medium">
              Enterprise Fleet Operations & Compliance Notice
            </p>
          </div>

          <div className="prose prose-slate max-w-none text-sm text-slate-600 space-y-5 leading-relaxed">
            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
                <span>1. Legal Entity & Platform Ownership</span>
              </h2>
              <p>
                The <strong>Trip Zoo</strong> software platform, including all related source code, progressive web application assets, Android application packages (.APK), databases, trademarks, and visual designs, is the proprietary property of Trip Zoo Fleet Operations.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
                <span>2. Compliance & Transport Regulations</span>
              </h2>
              <p>
                All transport records, trip verification timestamps, and fuel/diesel allocation entries generated by the platform are intended for operational auditing, fleet performance tracking, and internal billing verification. Users are required to adhere to all applicable national and local motor vehicle and transport regulations.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
                <span>3. Intellectual Property Rights</span>
              </h2>
              <p>
                All brand logos, graphic marks, interface elements, and custom typography contained within Trip Zoo are protected by applicable copyright and intellectual property laws. Reproduction or distribution without prior written authorization is strictly prohibited.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
                <span>4. Software Distribution & APK Packages</span>
              </h2>
              <p>
                The Trip Zoo Android APK is provided as a direct enterprise Progressive Web wrapper. Users must only download official application packages directly from authorized depot channels or the official Trip Zoo domain.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
                <span>5. Disclaimer of Warranties</span>
              </h2>
              <p>
                The software is provided &quot;as is&quot; without warranty of any kind, either express or implied, including but not limited to the fitness for a particular purpose, uninterrupted network availability, or battery efficiency on third-party mobile hardware.
              </p>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 text-xs py-4 px-4 text-center border-t border-slate-800 space-y-2">
        <div className="flex justify-center space-x-4 font-semibold">
          <Link href="/privacy" className="hover:text-slate-200">{t('common.privacyPolicy')}</Link>
          <span>•</span>
          <Link href="/terms" className="hover:text-slate-200">{t('common.termsOfService')}</Link>
          <span>•</span>
          <Link href="/legal" className="text-blue-400 hover:underline">{t('common.legalNotice')}</Link>
        </div>
        <p>© {new Date().getFullYear()} Trip Zoo. {t('common.allRightsReserved')}</p>
      </footer>
    </div>
  );
}
